# Generated by Django 2.2.4 on 2020-08-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('awards', models.TextField()),
                ('interests', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='main.User')),
            ],
        ),
    ]
