# Generated by Django 2.2.4 on 2020-08-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='degree_tittle',
            field=models.TextField(default='degree in science or whatever'),
        ),
        migrations.AddField(
            model_name='about',
            name='degree_type',
            field=models.TextField(default='bachalors of what'),
        ),
        migrations.AddField(
            model_name='about',
            name='gpa',
            field=models.TextField(default='your gpa'),
        ),
        migrations.AddField(
            model_name='about',
            name='job_name',
            field=models.TextField(default='job name'),
        ),
        migrations.AddField(
            model_name='about',
            name='job_title',
            field=models.TextField(default='job title'),
        ),
        migrations.AddField(
            model_name='about',
            name='skill_breakdown',
            field=models.TextField(default='breakdown'),
        ),
        migrations.AddField(
            model_name='about',
            name='start_to_end_job',
            field=models.TextField(default='start to end'),
        ),
        migrations.AddField(
            model_name='about',
            name='start_to_end_school',
            field=models.TextField(default='start school end school'),
        ),
    ]
